name: flutter_application_4
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  icons_launcher: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/Apoala.png
    - assets/images/Babes.png
    - assets/images/Bistrola 57.png
    - assets/images/Coyote Maya.png
    - assets/images/LogoFinal.png
    - assets/images/Pita Mediterranea.png
    - assets/images/Teya Santa Lucia.png

icons_launcher:
  image_path: "assets/images/ICON.png"
  platforms:
    android:
      enable: true
      adaptive_background_color: "#ffffff"
      adaptive_foreground_image: "assets/images/ICON.png"
    ios:
      enable: true